# The URL the site will be built for
base_url = "https://burakgungor.com"
title = "bgslabs"
description = "A data-driven engineering lab."

# Whether to generate feed files
generate_feeds = true
taxonomies = [{ name = "tags", feed = true },{ name = "categories", feed = true }]

[extra]
author = "Burak Güngör"
accent_color = "#0062ff" # IBM Blue

# Navigation
menu = [
        { name = "Blog", url = "/blog" },
        { name = "Projects", url = "/projects" },
        { name = "About", url = "/about" },
]

[markdown]
smart_punctuation = true
definition_list = true
github_alerts = true
render_emoji = true
[markdown.highlighting]
code = true
style = "class"
theme = "monokai"
